image:
  repository: ghcr.io/owner/llm-infer
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    cpu: 500m
    memory: 1Gi

service:
  type: ClusterIP
  port: 8000

env:
  MODEL_NAME: qwen2-7b


